name: Horusec Scan

on: workflow_dispatch

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Horusec
        env:
          HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "false"
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -p ./ --config-file-path=horusec-config.json -o="json" -O="./report.json" --return-error=false

      - name: Create Reports Directory
        run: mkdir -p ./reports
      
      - name: Save Report to Text File
        run: |
          more report.json
          cp report.json ./reports/report.json

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: horusec-report
          path: ./reports/report.json
