name: Horusec Scan

on: [push]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Horusec
        env:
          HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "false"
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -p ./ --config-file-path=horusec-config.json -O /reports/report.json --return-error=false
  
      - name: Save Report to Text File
        run: |
          cat /reports/report.json > /reports/horusec_report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: horusec-report
          path: horusec_report.txt
