name: Horusec Scan

on: workflow_dispatch

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Horusec          
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -p ./ --config-file-path=horusec-config.json -o="text" -O="./report.txt" --return-error=false

      - name: Create Reports Directory
        run: mkdir -p ./reports
      
      - name: Display report
        run: |
          more ./report.txt

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: horusec-report
          path: ./report.txt
